### PR TITLE
Adjust Styling

### PR DESCRIPTION
**Pull request by smolnar**
@philipdesmedt review pls. I'll remove the example post once you review.

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@smolnar I like this a lot, great improvements!

One thing I would like to see added though is a header on a blog post itself: http://localhost:4000/2014/12/01/example-content.html. The header can be as simple as putting the logo and name of the blog in the upper left corner, but this way it indicates better that they're still on the Intuo Nerds blog.

**Comment by smolnar** [comment]
Like this? I like this one :)

image

**Comment by philipdesmedt** [comment]
@smolnar yapp.. sounds good. We can still change if we need something less subtle. If we can push this, good for me to merge!

**Comment by smolnar** [comment]
@philipdesmedt thanks! I'll merge it and shortly the first blogpost is ready for review 😉

**Pull request merged**
